"""Added foreignkey between User and Food

Revision ID: b4665a9e2eb9
Revises: f8327bd2abe7
Create Date: 2020-02-13 15:55:55.657220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4665a9e2eb9'
down_revision = 'f8327bd2abe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_food_created_at'), 'food', ['created_at'], unique=False)
    op.create_foreign_key(None, 'food', 'users', ['user_id'], ['id'])
    op.drop_column('food', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('created_by', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_index(op.f('ix_food_created_at'), table_name='food')
    op.drop_column('food', 'user_id')
    # ### end Alembic commands ###
