"""empty message

Revision ID: d3215696e80d
Revises: 40b4d76b4ea8
Create Date: 2020-02-24 14:08:49.640795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3215696e80d'
down_revision = '40b4d76b4ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'is_public')
    # ### end Alembic commands ###
