"""empty message

Revision ID: f8327bd2abe7
Revises: 8bec726f17fb
Create Date: 2020-01-28 10:19:25.502394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8327bd2abe7'
down_revision = '8bec726f17fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('aws_key', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'food', ['aws_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food', type_='unique')
    op.drop_column('food', 'aws_key')
    # ### end Alembic commands ###
